# Generated by Django 4.0.2 on 2022-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
