# Generated by Django 4.0.2 on 2022-02-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0002_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashimg', models.FileField(upload_to='static')),
            ],
        ),
    ]
