# Generated by Django 4.0.2 on 2022-02-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0003_cash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cash',
            new_name='Dis',
        ),
    ]
