# Generated by Django 4.0.2 on 2022-02-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0005_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('count', models.IntegerField(null=True)),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acces.product')),
            ],
        ),
    ]
