# Generated by Django 4.0.2 on 2022-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='img',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
