# Generated by Django 4.0.2 on 2022-03-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0008_alter_dis_cashimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
