# Generated by Django 4.0.2 on 2022-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0009_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Confirm_Password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
