# Generated by Django 4.0.2 on 2022-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0011_remove_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
