# Generated by Django 4.0.2 on 2022-03-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces', '0012_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='paralex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallex', models.FileField(upload_to='static/img')),
            ],
        ),
    ]
